services:
  fiubamientoapi:
    build: ./backend 
    image: fiubamiento_backend:v1 
    ports:
      - "3000:3000"
    command: npx nodemon app.js
    volumes:
      - ./backend/app:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASS: post
      DB_NAME: FIUBAMIENTO
    container_name: fiubamiento_api
  
  db:
    image: postgres:17
    container_name: fiubamiento_db
    environment:
     POSTGRES_USER: "postgres"
     POSTGRES_PASSWORD: "post"
     POSTGRES_DB: FIUBAMIENTO
    ports:
      - "5433:5432"
    volumes:
      - ./backend/data:/docker-entrypoint-initdb.d
      - ./backend/db_data:/var/lib/postgresql/data
  
  frontend:
    image: nginx:latest
    container_name: fiubamiento_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

