services:
  pokeapi:
    build: . #builder el dockerfile de esta carpeta
    image: fiubamiento_backend:v1 
    ports:
      - "3000:3000"
    depends_on:
      - db
      #env_file: ./.env
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: post
      DB_NAME: FIUBAMIENTO
  
  db:
    image: postgres:17
    container_name: fiubamiento_db
    environment:
     POSTGRES_USER: "postgres"
     POSTGRES_PASSWORD: "post"
     POSTGRES_DB: FIUBAMIENTO
    ports:
      - "5433:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

